### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by sami-soft** [void-stack/VMUnprotect.Dumper#3]
Unhandled Exception: System.ArgumentException: Absolute path information is required.

   at System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String path)
   at System.Reflection.Assembly.LoadFile(String path)
   at Program.<Main>$(String[] args) in C:\Users\hussa\Desktop\VMUnprotect.Dumper\VMUnprotect.Dumper\Program.cs:line 40

**Comment by 0xviolation** [comment]
Either copy the file into VMUnprotect Dumper dir or provide exact path like C:\foo\bar.exe
